from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from stock_rtx4060.krx_calendar import KRX_CALENDAR_FIXTURE_PATH, generate_krx_calendar_fixture


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the checked-in KRX trading calendar fixture from PyKRX.")
    parser.add_argument("--from-date", default="20260101", help="Start date in YYYYMMDD or YYYY-MM-DD format.")
    parser.add_argument("--to-date", default="20261231", help="End date in YYYYMMDD or YYYY-MM-DD format.")
    parser.add_argument("--output", default=str(KRX_CALENDAR_FIXTURE_PATH), help="Output fixture path.")
    args = parser.parse_args()

    from pykrx import stock

    days = stock.get_previous_business_days(fromdate=_compact(args.from_date), todate=_compact(args.to_date))
    normalized = [str(day)[:10] for day in days]
    if not normalized:
        raise SystemExit("PyKRX returned no business days; fixture was not updated.")

    output = generate_krx_calendar_fixture(
        args.output,
        start_date=_iso(args.from_date),
        end_date=_iso(args.to_date),
        trading_days=normalized,
        source_status="generated_from_pykrx",
        notes=[
            "Generated by tools/generate_krx_calendar_fixture.py.",
            "Unit tests must read this fixture and must not call network providers for calendar decisions.",
        ],
    )
    print(output)
    return 0


def _compact(value: str) -> str:
    return value.replace("-", "")


def _iso(value: str) -> str:
    compact = _compact(value)
    return f"{compact[:4]}-{compact[4:6]}-{compact[6:8]}"


if __name__ == "__main__":
    raise SystemExit(main())
